server:
    type: simple
    applicationContextPath: /
    adminContextPath: /management
    connector:
        type: http
        port: ${PORT}

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    com.ewcikyr.accounts: DEBUG
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      target: stdout
      logFormat: "[%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
